services:
    postgres-14:
        image: docker.io/postgres:14-alpine
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=me
    postgres-15:
        image: docker.io/postgres:15-alpine
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=me
    postgres-16:
        image: docker.io/postgres:16-alpine
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=me
    postgres-17:
        image: docker.io/postgres:17-alpine
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=me
    db-dump-agent:
        build:
            context: .
        ports:
            - 1880:1880
        volumes:
            - .:/data
            - postgres-dump:/dumps
        environment:
            - ENABLE_EDITOR=true
            - DUMP_DIRECTORY=/dumps
            - RETENTION_DUMPS=10
            - SECRET_KEY="averysecretkeyforencryptpasswords"

volumes:
    postgres-dump:
        driver: local
